import type { Locale } from "../i18n";
import { cookieValue } from "../utils";
import { brandMark, page } from "./shared";

export const adminLocale = (request: Request): Locale =>
  cookieValue(request, "memboux_admin_locale") === "el" ? "el" : "en";
export function adminShell(title: string, content: string, locale:Locale="en") {
  return page(`${title} – Memboux Admin`, `<style>.admin-ui,.admin-ui button,.admin-ui input,.admin-ui select,.admin-ui textarea{font-family:'Noto Serif',serif}.admin-ui{font-weight:300}.admin-ui h1,.admin-ui h2,.admin-ui h3{font-family:'Noto Serif',serif;font-weight:400}.admin-ui strong{font-weight:500}</style><div class="admin-ui"><header class="border-b bg-[#33251f] text-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">${brandMark("/admin", true, true)}<div class="flex items-center gap-2"><a href="/admin/language/${locale==="el"?"en":"el"}" class="rounded-lg border border-white/20 px-3 py-2 text-sm">${locale==="el"?"EN":"EL"}</a><div class="group relative"><button class="flex items-center gap-2 rounded-xl border border-white/20 px-4 py-2 text-sm hover:bg-white/10"><span class="flex h-7 w-7 items-center justify-center rounded-full bg-white/15">A</span>Admin <span>⌄</span></button><div class="invisible absolute right-0 top-full z-40 w-56 translate-y-1 rounded-2xl border border-[#ddd0c6] bg-white p-2 text-[#2b211d] opacity-0 shadow-2xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100"><a href="/admin" class="block rounded-xl px-3 py-2 text-sm hover:bg-[#f6f1eb]">${locale==="el"?"Βιβλιοθήκη events":"Event library"}</a><a href="/admin/reported" class="block rounded-xl px-3 py-2 text-sm hover:bg-[#f6f1eb]">${locale==="el"?"Reported φωτογραφίες":"Reported media"}</a><a href="/admin/privacy-requests" class="block rounded-xl px-3 py-2 text-sm hover:bg-[#f6f1eb]">${locale==="el"?"Αιτήματα απορρήτου":"Privacy requests"}</a><a href="/admin/trash" class="block rounded-xl px-3 py-2 text-sm hover:bg-[#f6f1eb]">${locale==="el"?"Κάδος φωτογραφιών":"Media trash"}</a><form action="/admin/logout" method="post" class="mt-1 border-t"><button class="w-full rounded-xl px-3 py-3 text-left text-sm text-red-700 hover:bg-red-50">${locale==="el"?"Αποσύνδεση":"Sign out"}</button></form></div></div></div></div></header>${content}</div>`);
}
