import { t, type Locale } from "../i18n";
import { brandMark, googleIcon, page } from "./shared";

export function authPage(locale: Locale, mode: "login" | "register") {
  const m = t(locale);
  const isRegister = mode === "register";
  return page(`${isRegister ? m.register : m.login} – Memboux`, `<main class="flex min-h-screen items-center justify-center p-5"><section class="w-full max-w-md rounded-3xl border border-[#ddd0c6] bg-white/95 p-8 shadow-[0_24px_70px_rgba(71,50,40,.12)]"><div class="mb-7 flex items-center justify-between">${brandMark(`/${locale}`, true)}<a href="/${locale === "el" ? "en" : "el"}/${mode}" class="text-sm font-medium text-[#6e4f3e]">${locale === "el" ? "EN" : "EL"}</a></div><h1 class="text-4xl">${isRegister ? m.register : m.login}</h1><button id="google" class="mt-6 flex w-full items-center justify-center gap-3 rounded-xl border border-[#d8ccc3] bg-white px-4 py-3 font-medium shadow-sm transition hover:border-[#a47c65] hover:bg-[#fbf8f4]">${googleIcon()}<span>${m.continueGoogle}</span></button><div class="my-5 flex items-center gap-3 text-xs text-slate-400"><span class="h-px flex-1 bg-slate-200"></span>OR<span class="h-px flex-1 bg-slate-200"></span></div><form id="authForm" class="space-y-3">${isRegister ? `<input name="name" required maxlength="100" placeholder="${m.name}" class="w-full rounded-xl border px-4 py-3">` : ""}<input name="email" type="email" required autocomplete="email" placeholder="${m.email}" class="w-full rounded-xl border px-4 py-3"><input name="password" type="password" required minlength="10" autocomplete="${isRegister ? "new-password" : "current-password"}" placeholder="${m.password}" class="w-full rounded-xl border px-4 py-3"><p id="error" class="hidden rounded-xl bg-red-50 p-3 text-sm text-red-700"></p><button class="w-full rounded-xl bg-[#33251f] py-3 font-semibold text-white">${isRegister ? m.register : m.login}</button></form>${!isRegister ? `<a href="/${locale}/forgot-password" class="mt-4 block text-center text-sm text-[#6e4f3e]">${m.forgotPassword}</a>` : ""}<p class="mt-6 text-center text-sm text-[#625750]">${isRegister ? m.hasAccount : m.noAccount} <a class="font-semibold text-[#6e4f3e]" href="/${locale}/${isRegister ? "login" : "register"}">${isRegister ? m.login : m.register}</a></p></section></main><script>
const locale=${JSON.stringify(locale)};const error=document.getElementById('error');
document.getElementById('google').onclick=async()=>{const r=await fetch('/api/auth/sign-in/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:'google',callbackURL:'/'+locale+'/account'})});const d=await r.json();if(d.url)location.href=d.url;else{error.textContent=d.message||${JSON.stringify(m.genericError)};error.classList.remove('hidden')}};
document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();error.classList.add('hidden');const values=Object.fromEntries(new FormData(e.target));const r=await fetch('/api/auth/${isRegister ? "sign-up" : "sign-in"}/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,callbackURL:'/'+locale+'/account'})});const d=await r.json().catch(()=>({}));if(r.ok){location.href=${isRegister ? `'/${locale}/verify-email'` : `'/${locale}/account'`}}else{error.textContent=d.message||${JSON.stringify(m.genericError)};error.classList.remove('hidden')}};
<\/script>`);
}
