import { eventTypeLabel, type EventType } from "../event-types";
import { commerceAlbumLimit, commerceProductName, commerceUploadWindowDays, formatCommerceMoney, type CommerceProduct } from "../commerce";
import type { Locale } from "../i18n";
import { esc } from "../utils";

type MarketingCopy = {
  exploreEyebrow: string; exploreTitle: string; exploreText: string; exploreAction: string; allEvents: string;
  demoEyebrow: string; demoTitle: string; demoText: string; demoAction: string; weddingDemo: string; demoFrame: string;
  pricingEyebrow: string; pricingTitle: string; pricingText: string; free: string; oneTime: string; popular: string;
  startFree: string; createEvent: string; unavailable: string; days: string; files: string; originals: string;
  noOriginals: string; included: string; extended: string; bestFor: [string, string, string];
  proEyebrow: string; proTitle: string; proText: string; proAction: string; proNote: string;
  faqEyebrow: string; faqTitle: string; faqs: Array<[string, string]>;
};

const copy: Record<Locale, MarketingCopy> = {
  en: {
    exploreEyebrow: "Made for real events", exploreTitle: "Choose your event. Memboux shapes the experience.", exploreText: "Start with a purpose-built page, guided setup and a real preview before you invite anyone.", exploreAction: "Explore", allEvents: "See every event type",
    demoEyebrow: "Try it before you create it", demoTitle: "This is what your guests will actually use.", demoText: "Open the live, no-account simulation. Test the gallery, guestbook and contribution flow on desktop or mobile.", demoAction: "Open interactive demo", weddingDemo: "See wedding demo", demoFrame: "Interactive birthday event demo",
    pricingEyebrow: "Simple event pricing", pricingTitle: "Start free. Upgrade the event, not every guest.", pricingText: "Guests never pay. Choose a one-time package when you need more capacity, originals and longer access.", free: "Memboux Free", oneTime: "One-time", popular: "Most popular", startFree: "Start free", createEvent: "Create event", unavailable: "Paid checkout is not live yet. No card details are collected.", days: "days access", files: "photos & videos", originals: "Original downloads", noOriginals: "Preview downloads only", included: "Included", extended: "Long-term access", bestFor: ["Trying a real event", "Weddings, parties and trips", "Large celebrations and communities"],
    proEyebrow: "For event professionals", proTitle: "A polished client experience, under one organized workflow.", proText: "Planners, photographers and venues will be able to create client events, collaborate with couples and keep every delivery in one workspace.", proAction: "Create a professional profile", proNote: "Professional subscriptions and capacity plans are in preparation; no subscription is charged today.",
    faqEyebrow: "Questions, answered", faqTitle: "Everything you need to start with confidence.", faqs: [["Do guests need an app or account?", "No app is required. Guests open the event link or QR in their browser and contribute under the event’s access settings."], ["Who owns the uploaded memories?", "The event remains controlled by its owners. Memboux does not use private event media as advertising inventory."], ["What happens when Memboux Free ends?", "Public access and new uploads pause, while the dashboard, preview and existing memories remain safe for the organizer."], ["Can I see the event before publishing?", "Yes. Every supported event type has a guided setup and a full private preview before guest access is activated."], ["Are payments active?", "Not yet. Package prices are visible for transparency, but Memboux does not currently collect card details or charge customers."]],
  },
  el: {
    exploreEyebrow: "Φτιαγμένο για αληθινά events", exploreTitle: "Διάλεξε το event. Το Memboux προσαρμόζει την εμπειρία.", exploreText: "Ξεκίνα με ειδική σελίδα, καθοδηγούμενο στήσιμο και πραγματικό preview πριν προσκαλέσεις οποιονδήποτε.", exploreAction: "Εξερεύνηση", allEvents: "Όλοι οι τύποι event",
    demoEyebrow: "Δοκίμασέ το πριν το δημιουργήσεις", demoTitle: "Αυτό ακριβώς θα χρησιμοποιήσουν οι καλεσμένοι σου.", demoText: "Άνοιξε το διαδραστικό demo χωρίς λογαριασμό. Δοκίμασε gallery, ευχολόγιο και upload από υπολογιστή ή κινητό.", demoAction: "Άνοιγμα διαδραστικού demo", weddingDemo: "Demo γάμου", demoFrame: "Διαδραστικό demo event γενεθλίων",
    pricingEyebrow: "Απλή τιμολόγηση ανά event", pricingTitle: "Ξεκίνα δωρεάν. Αναβάθμισε το event, όχι κάθε καλεσμένο.", pricingText: "Οι καλεσμένοι δεν πληρώνουν ποτέ. Επίλεξε εφάπαξ πακέτο όταν χρειάζεσαι μεγαλύτερη χωρητικότητα, πρωτότυπα και πρόσβαση μεγαλύτερης διάρκειας.", free: "Memboux Free", oneTime: "Εφάπαξ", popular: "Δημοφιλές", startFree: "Ξεκίνα δωρεάν", createEvent: "Δημιουργία event", unavailable: "Οι πληρωμές δεν έχουν ενεργοποιηθεί ακόμη. Δεν συλλέγονται στοιχεία κάρτας.", days: "ημέρες πρόσβασης", files: "φωτογραφίες & βίντεο", originals: "Λήψη πρωτοτύπων", noOriginals: "Μόνο preview λήψεις", included: "Περιλαμβάνεται", extended: "Μακροχρόνια πρόσβαση", bestFor: ["Δοκιμή πραγματικού event", "Γάμους, πάρτι και ταξίδια", "Μεγάλες εκδηλώσεις και κοινότητες"],
    proEyebrow: "Για επαγγελματίες event", proTitle: "Premium εμπειρία πελάτη, σε μία οργανωμένη ροή.", proText: "Planners, φωτογράφοι και χώροι εκδηλώσεων θα μπορούν να δημιουργούν events πελατών, να συνεργάζονται με ζευγάρια και να οργανώνουν κάθε παράδοση σε ένα workspace.", proAction: "Δημιουργία επαγγελματικού προφίλ", proNote: "Οι επαγγελματικές συνδρομές και τα όρια ενεργών events ετοιμάζονται· σήμερα δεν γίνεται καμία χρέωση.",
    faqEyebrow: "Απαντήσεις χωρίς ψιλά γράμματα", faqTitle: "Όσα χρειάζεσαι για να ξεκινήσεις με σιγουριά.", faqs: [["Χρειάζονται app ή λογαριασμό οι καλεσμένοι;", "Όχι. Ανοίγουν το link ή το QR στον browser και συμμετέχουν σύμφωνα με τις ρυθμίσεις πρόσβασης του event."], ["Ποιος ελέγχει τις αναμνήσεις;", "Το event παραμένει υπό τον έλεγχο των owners. Το Memboux δεν χρησιμοποιεί ιδιωτικό υλικό εκδηλώσεων για διαφημίσεις."], ["Τι γίνεται όταν λήξει το Memboux Free;", "Η δημόσια πρόσβαση και τα νέα uploads παγώνουν, αλλά το dashboard, το preview και οι υπάρχουσες αναμνήσεις παραμένουν ασφαλή."], ["Μπορώ να δω το event πριν δημοσιευτεί;", "Ναι. Κάθε υποστηριζόμενος τύπος έχει wizard και πλήρες ιδιωτικό preview πριν ενεργοποιηθεί η πρόσβαση καλεσμένων."], ["Λειτουργούν ήδη οι πληρωμές;", "Όχι ακόμη. Οι τιμές εμφανίζονται για διαφάνεια, αλλά το Memboux δεν συλλέγει στοιχεία κάρτας και δεν πραγματοποιεί χρεώσεις."]],
  },
  fr: {
    exploreEyebrow: "Conçu pour de vrais événements", exploreTitle: "Choisissez votre événement. Memboux adapte l’expérience.", exploreText: "Commencez avec une page dédiée, une configuration guidée et un aperçu réel avant toute invitation.", exploreAction: "Découvrir", allEvents: "Voir tous les événements",
    demoEyebrow: "Essayez avant de créer", demoTitle: "Voici l’expérience réelle de vos invités.", demoText: "Testez sans compte la galerie, le livre d’or et l’ajout de photos sur ordinateur ou mobile.", demoAction: "Ouvrir la démo interactive", weddingDemo: "Voir la démo mariage", demoFrame: "Démo interactive d’anniversaire",
    pricingEyebrow: "Tarifs simples par événement", pricingTitle: "Commencez gratuitement. Améliorez l’événement, pas chaque invité.", pricingText: "Les invités ne paient jamais. Choisissez un forfait unique pour plus de capacité, les originaux et un accès prolongé.", free: "Memboux Free", oneTime: "Paiement unique", popular: "Populaire", startFree: "Commencer gratuitement", createEvent: "Créer un événement", unavailable: "Le paiement n’est pas encore actif. Aucune carte n’est collectée.", days: "jours d’accès", files: "photos et vidéos", originals: "Téléchargement des originaux", noOriginals: "Aperçus uniquement", included: "Inclus", extended: "Accès longue durée", bestFor: ["Tester un vrai événement", "Mariages, fêtes et voyages", "Grandes célébrations et communautés"],
    proEyebrow: "Pour les professionnels", proTitle: "Une expérience client soignée, dans un flux organisé.", proText: "Organisateurs, photographes et lieux pourront créer des événements clients et collaborer dans un espace unique.", proAction: "Créer un profil professionnel", proNote: "Les abonnements professionnels sont en préparation; aucun abonnement n’est facturé aujourd’hui.",
    faqEyebrow: "Questions fréquentes", faqTitle: "Tout pour commencer sereinement.", faqs: [["Les invités ont-ils besoin d’une application?", "Non. Ils ouvrent le lien ou le QR dans leur navigateur."], ["Qui contrôle les souvenirs?", "Les propriétaires de l’événement gardent le contrôle. Les médias privés ne servent pas à la publicité."], ["Que se passe-t-il à la fin de Memboux Free?", "L’accès public et les nouveaux ajouts sont suspendus, mais les souvenirs existants restent en sécurité."], ["Puis-je voir l’événement avant publication?", "Oui, chaque type propose une configuration guidée et un aperçu privé complet."], ["Les paiements sont-ils actifs?", "Pas encore. Les prix sont transparents, mais aucune carte n’est collectée."]],
  },
  de: {
    exploreEyebrow: "Für echte Events gemacht", exploreTitle: "Wähle dein Event. Memboux gestaltet das Erlebnis.", exploreText: "Starte mit einer passenden Seite, geführter Einrichtung und echter Vorschau, bevor du Gäste einlädst.", exploreAction: "Entdecken", allEvents: "Alle Event-Arten",
    demoEyebrow: "Vor dem Erstellen testen", demoTitle: "Genau das werden deine Gäste nutzen.", demoText: "Teste Galerie, Gästebuch und Upload ohne Konto auf Desktop oder Smartphone.", demoAction: "Interaktive Demo öffnen", weddingDemo: "Hochzeitsdemo ansehen", demoFrame: "Interaktive Geburtstagsdemo",
    pricingEyebrow: "Einfache Event-Preise", pricingTitle: "Kostenlos starten. Das Event upgraden, nicht jeden Gast.", pricingText: "Gäste zahlen nie. Einmalige Pakete bieten mehr Kapazität, Originale und längeren Zugriff.", free: "Memboux Free", oneTime: "Einmalig", popular: "Beliebt", startFree: "Kostenlos starten", createEvent: "Event erstellen", unavailable: "Zahlungen sind noch nicht aktiv. Es werden keine Kartendaten erfasst.", days: "Tage Zugriff", files: "Fotos & Videos", originals: "Original-Downloads", noOriginals: "Nur Vorschau", included: "Enthalten", extended: "Langfristiger Zugriff", bestFor: ["Ein echtes Event testen", "Hochzeiten, Partys und Reisen", "Große Feiern und Communities"],
    proEyebrow: "Für Event-Profis", proTitle: "Ein hochwertiges Kundenerlebnis in einem organisierten Ablauf.", proText: "Planer, Fotografen und Locations werden Kunden-Events erstellen und gemeinsam verwalten können.", proAction: "Professionelles Profil erstellen", proNote: "Professionelle Abos sind in Vorbereitung; heute wird kein Abo berechnet.",
    faqEyebrow: "Häufige Fragen", faqTitle: "Alles für einen sicheren Start.", faqs: [["Brauchen Gäste eine App?", "Nein. Link oder QR öffnen sich direkt im Browser."], ["Wer kontrolliert die Erinnerungen?", "Die Event-Eigentümer behalten die Kontrolle. Private Medien werden nicht für Werbung verwendet."], ["Was passiert nach Memboux Free?", "Öffentlicher Zugriff und neue Uploads pausieren; vorhandene Erinnerungen bleiben sicher."], ["Gibt es vorab eine Vorschau?", "Ja. Jeder Event-Typ hat eine geführte Einrichtung und private Vorschau."], ["Sind Zahlungen aktiv?", "Noch nicht. Preise sind sichtbar, Kartendaten werden aber nicht erfasst."]],
  },
  es: {
    exploreEyebrow: "Creado para eventos reales", exploreTitle: "Elige tu evento. Memboux adapta la experiencia.", exploreText: "Empieza con una página específica, configuración guiada y una vista previa real antes de invitar.", exploreAction: "Explorar", allEvents: "Ver todos los eventos",
    demoEyebrow: "Pruébalo antes de crearlo", demoTitle: "Esto es lo que usarán realmente tus invitados.", demoText: "Prueba sin cuenta la galería, el libro de visitas y las subidas desde ordenador o móvil.", demoAction: "Abrir demo interactiva", weddingDemo: "Ver demo de boda", demoFrame: "Demo interactiva de cumpleaños",
    pricingEyebrow: "Precios sencillos por evento", pricingTitle: "Empieza gratis. Mejora el evento, no a cada invitado.", pricingText: "Los invitados nunca pagan. Elige un paquete único para más capacidad, originales y acceso prolongado.", free: "Memboux Free", oneTime: "Pago único", popular: "Popular", startFree: "Empezar gratis", createEvent: "Crear evento", unavailable: "Los pagos aún no están activos. No se recopilan tarjetas.", days: "días de acceso", files: "fotos y vídeos", originals: "Descarga de originales", noOriginals: "Solo vista previa", included: "Incluido", extended: "Acceso prolongado", bestFor: ["Probar un evento real", "Bodas, fiestas y viajes", "Grandes celebraciones y comunidades"],
    proEyebrow: "Para profesionales", proTitle: "Una experiencia de cliente cuidada en un flujo organizado.", proText: "Organizadores, fotógrafos y espacios podrán crear eventos de clientes y colaborar en un solo espacio.", proAction: "Crear perfil profesional", proNote: "Las suscripciones profesionales están en preparación; hoy no se cobra ninguna.",
    faqEyebrow: "Preguntas frecuentes", faqTitle: "Todo para empezar con confianza.", faqs: [["¿Los invitados necesitan una app?", "No. Abren el enlace o QR directamente en el navegador."], ["¿Quién controla los recuerdos?", "Los propietarios del evento mantienen el control. Los medios privados no se usan para publicidad."], ["¿Qué ocurre al terminar Memboux Free?", "El acceso público y las nuevas subidas se pausan; los recuerdos existentes siguen seguros."], ["¿Puedo verlo antes de publicar?", "Sí. Cada tipo tiene configuración guiada y vista previa privada."], ["¿Están activos los pagos?", "Todavía no. Los precios son visibles, pero no se recopilan datos de tarjeta."]],
  },
  it: {
    exploreEyebrow: "Pensato per eventi reali", exploreTitle: "Scegli il tuo evento. Memboux adatta l’esperienza.", exploreText: "Inizia con una pagina dedicata, configurazione guidata e anteprima reale prima di invitare qualcuno.", exploreAction: "Esplora", allEvents: "Vedi tutti gli eventi",
    demoEyebrow: "Provalo prima di crearlo", demoTitle: "Questa è l’esperienza reale dei tuoi invitati.", demoText: "Prova senza account galleria, guestbook e upload da desktop o smartphone.", demoAction: "Apri la demo interattiva", weddingDemo: "Vedi demo matrimonio", demoFrame: "Demo interattiva di compleanno",
    pricingEyebrow: "Prezzi semplici per evento", pricingTitle: "Inizia gratis. Fai l’upgrade dell’evento, non di ogni invitato.", pricingText: "Gli invitati non pagano mai. Scegli un pacchetto una tantum per più capacità, originali e accesso prolungato.", free: "Memboux Free", oneTime: "Una tantum", popular: "Popolare", startFree: "Inizia gratis", createEvent: "Crea evento", unavailable: "I pagamenti non sono ancora attivi. Nessuna carta viene raccolta.", days: "giorni di accesso", files: "foto e video", originals: "Download originali", noOriginals: "Solo anteprima", included: "Incluso", extended: "Accesso prolungato", bestFor: ["Provare un evento reale", "Matrimoni, feste e viaggi", "Grandi celebrazioni e community"],
    proEyebrow: "Per professionisti", proTitle: "Un’esperienza cliente curata in un flusso organizzato.", proText: "Planner, fotografi e location potranno creare eventi cliente e collaborare in un unico workspace.", proAction: "Crea profilo professionale", proNote: "Gli abbonamenti professionali sono in preparazione; oggi non viene addebitato nulla.",
    faqEyebrow: "Domande frequenti", faqTitle: "Tutto per iniziare con fiducia.", faqs: [["Gli invitati devono installare un’app?", "No. Aprono link o QR direttamente nel browser."], ["Chi controlla i ricordi?", "I proprietari dell’evento mantengono il controllo. I media privati non sono usati per pubblicità."], ["Cosa succede dopo Memboux Free?", "Accesso pubblico e nuovi upload si fermano; i ricordi esistenti restano al sicuro."], ["Posso vedere l’evento prima di pubblicarlo?", "Sì. Ogni tipo offre configurazione guidata e anteprima privata."], ["I pagamenti sono attivi?", "Non ancora. I prezzi sono visibili, ma non vengono raccolte carte."]],
  },
};

const uploadDaysLabel: Record<Locale, string> = {
  en: "upload days",
  el: "ημέρες uploads",
  fr: "jours de dépôt",
  de: "Upload-Tage",
  es: "días de subida",
  it: "giorni di caricamento",
};

const featuredEvents: Array<{ type: EventType; symbol: string; color: string }> = [
  { type: "wedding", symbol: "♡", color: "#ff5f7e" },
  { type: "bachelor", symbol: "✦", color: "#7152f3" },
  { type: "birthday", symbol: "★", color: "#f59e0b" },
  { type: "baptism", symbol: "◌", color: "#17b8a6" },
  { type: "trip", symbol: "↗", color: "#3b82f6" },
  { type: "corporate", symbol: "◇", color: "#475569" },
];

export function homeCommercialSections(locale: Locale, products: CommerceProduct[]) {
  const t = copy[locale];
  const eventCards = featuredEvents.map(({ type, symbol, color }) => {
    const base = type === "wedding" ? `/${locale}/wedding` : `/${locale}/events/${type}`;
    return `<article class="home-event-card mbx-card group flex min-h-52 flex-col p-5 sm:p-6"><span class="flex h-11 w-11 items-center justify-center rounded-2xl text-xl font-bold" style="background:${color}18;color:${color}">${symbol}</span><h3 class="mt-7 text-xl">${esc(eventTypeLabel(type, locale))}</h3><div class="mt-auto flex items-center justify-between gap-3 pt-6"><a data-marketing-action="event-${type}" href="${base}" class="text-sm font-bold text-[#4d2fbd]">${esc(t.exploreAction)} →</a><a href="${base}/preview" class="rounded-full border border-[#e5e0f0] px-3 py-1.5 text-xs font-semibold text-[#70667d]">Demo</a></div></article>`;
  }).join("");

  const plans = products.slice(0, 3).map((product, index) => ({
      key: product.product_key,
      name: commerceProductName(product, locale),
      price: formatCommerceMoney(product.amount_minor, product.currency, locale),
      badge: product.amount_minor === 0 ? t.included : index === 1 ? t.popular : t.extended,
      files: product.media_limit?.toLocaleString(locale) ?? "—",
      uploadDays: commerceUploadWindowDays(product),
      days: product.event_duration_days ? String(product.event_duration_days) : "",
      original: `${commerceAlbumLimit(product)} custom albums · ${product.product_key === "event_free" ? "No Official Album" : "Official Album"} · ${product.original_downloads_enabled ? t.originals : t.noOriginals}`,
      best: t.bestFor[index] ?? t.bestFor[0],
      featured: index === 1,
      free: product.amount_minor === 0,
    }));
  const planCards = plans.map((plan) => `<article class="home-plan-card relative flex flex-col rounded-[1.25rem] border ${plan.featured ? "border-[#cfc7df] bg-[#f0edf5] text-[#302b38] shadow-[0_16px_42px_rgba(57,48,69,.09)]" : "border-[#e5e1e9] bg-white text-[#302b38]"} p-6 sm:p-8"><span class="w-fit rounded-full ${plan.featured ? "bg-[#ded7ec] text-[#57468e]" : "bg-[#f4f1f7] text-[#675885]"} px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.13em]">${esc(plan.badge)}</span><h3 class="mt-6 text-2xl">${esc(plan.name)}</h3><div class="mt-3 flex items-end gap-2"><strong class="text-5xl tracking-[-.06em]">${plan.price}</strong>${!plan.free ? `<span class="pb-1 text-sm opacity-65">${esc(t.oneTime)}</span>` : ""}</div><p class="mt-5 text-sm font-semibold opacity-70">${esc(plan.best)}</p><ul class="mt-7 space-y-3 text-sm"><li>✓ ${plan.files} ${esc(t.files)}</li><li>✓ ${plan.uploadDays} ${esc(uploadDaysLabel[locale])}</li>${plan.days ? `<li>✓ ${plan.days} ${esc(t.days)}</li>` : ""}<li>✓ ${esc(plan.original)}</li><li>✓ Gallery · Guestbook · Slideshow</li></ul><a data-marketing-action="plan-${esc(plan.key)}" href="/${locale}/register" class="mbx-button mbx-button--primary mt-8">${plan.free ? esc(t.startFree) : esc(t.createEvent)}</a></article>`).join("");
  const faqItems = t.faqs.map(([question, answer], index) => `<details class="group border-b border-[#e5e0f0] py-5" ${index === 0 ? "open" : ""}><summary class="flex min-h-11 cursor-pointer list-none items-center justify-between gap-5 text-left font-bold text-[#20152f]"><span>${esc(question)}</span><span aria-hidden="true" class="text-xl text-[#7152f3] transition group-open:rotate-45">+</span></summary><p class="max-w-3xl pb-2 pr-10 text-sm leading-7 text-[#70667d]">${esc(answer)}</p></details>`).join("");

  return `<section id="event-types" class="mbx-section scroll-mt-24 bg-[#f8f7fc]"><div class="mbx-container"><div class="max-w-3xl"><p class="mbx-eyebrow">${esc(t.exploreEyebrow)}</p><h2 class="mbx-title mt-4">${esc(t.exploreTitle)}</h2><p class="mbx-lead mt-5">${esc(t.exploreText)}</p></div><div class="home-event-grid mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">${eventCards}</div><a href="/${locale}/register" class="mbx-button mbx-button--secondary mt-8">${esc(t.allEvents)} →</a></div></section>
  <section id="demo" class="mbx-section scroll-mt-24 overflow-hidden border-y border-[#e7e3eb] bg-[#f1eef5] text-[#302b38]"><div class="home-demo-grid mbx-container grid items-center gap-12 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><div><p class="mbx-eyebrow">${esc(t.demoEyebrow)}</p><h2 class="mbx-title mt-4">${esc(t.demoTitle)}</h2><p class="mt-5 max-w-xl text-base leading-8 text-[#756f7c]">${esc(t.demoText)}</p><div class="home-demo-actions mt-8 flex flex-col gap-3 sm:flex-row"><a data-marketing-action="event-demo" href="/${locale}/events/birthday/preview?theme=vivid" class="mbx-button mbx-button--primary">${esc(t.demoAction)}</a><a data-marketing-action="wedding-demo" href="/${locale}/wedding/preview?theme=nocturne" class="mbx-button border border-[#d7d1df] bg-white text-[#514a58]">${esc(t.weddingDemo)}</a></div></div><div class="home-demo-stage mx-auto w-full max-w-[46rem] rounded-[1.5rem] border border-[#ddd7e4] p-3 shadow-[0_22px_60px_rgba(57,48,69,.1)] sm:p-5"><div class="overflow-hidden rounded-[1.1rem] bg-white"><iframe loading="lazy" title="${esc(t.demoFrame)}" src="/${locale}/events/birthday/demo-frame?theme=vivid" class="h-[35rem] w-full border-0" sandbox="allow-scripts allow-forms allow-same-origin"></iframe></div></div></div></section>
  <section id="pricing" class="mbx-section scroll-mt-24 bg-[#f8f7fc]"><div class="mbx-container"><div class="mx-auto max-w-3xl text-center"><p class="mbx-eyebrow">${esc(t.pricingEyebrow)}</p><h2 class="mbx-title mt-4">${esc(t.pricingTitle)}</h2><p class="mbx-lead mx-auto mt-5">${esc(t.pricingText)}</p></div><div class="home-plan-grid mt-12 grid items-stretch gap-5 lg:grid-cols-3">${planCards}</div><p class="home-pricing-note mx-auto mt-7 max-w-2xl rounded-full bg-[#fff4d6] px-5 py-3 text-center text-xs font-semibold text-[#795b12]">${esc(t.unavailable)}</p></div></section>
  <section class="px-4 pb-16 sm:px-6 sm:pb-24"><div class="mbx-container overflow-hidden rounded-[1.5rem] border border-[#ddd7e4] bg-[#eeeaf4] p-7 text-[#302b38] shadow-[0_18px_50px_rgba(57,48,69,.08)] sm:p-12 lg:grid lg:grid-cols-[1fr_auto] lg:items-end lg:gap-12"><div><p class="mbx-eyebrow">${esc(t.proEyebrow)}</p><h2 class="mbx-title mt-4 max-w-3xl">${esc(t.proTitle)}</h2><p class="mt-5 max-w-3xl leading-7 text-[#6f6876]">${esc(t.proText)}</p><p class="mt-4 max-w-3xl text-xs leading-5 text-[#8b8491]">${esc(t.proNote)}</p></div><a data-marketing-action="professional-profile" href="/${locale}/register" class="mbx-button mbx-button--primary mt-8 lg:mt-0">${esc(t.proAction)}</a></div></section>
  <section id="faq" class="home-faq scroll-mt-24 bg-white py-14 sm:py-18 lg:py-20"><div class="mbx-container grid gap-10 lg:grid-cols-[.65fr_1.35fr] lg:gap-20"><div><p class="mbx-eyebrow">${esc(t.faqEyebrow)}</p><h2 class="mbx-title mt-4">${esc(t.faqTitle)}</h2></div><div>${faqItems}</div></div></section>
  <script>(()=>{if(window.__membouxMarketingActions)return;window.__membouxMarketingActions=true;document.addEventListener('click',event=>{const link=event.target.closest?.('[data-marketing-action]');if(!link)return;window.dispatchEvent(new CustomEvent('memboux:marketing-action',{detail:{action:link.dataset.marketingAction}}))})})()<\/script>`;
}
