import type { EventType } from "./event-types";
import type { Locale } from "./i18n";

type Bilingual = { en: string; el: string };

export type EventVertical = {
  type: Exclude<EventType, "wedding">;
  symbol: string;
  eyebrow: Bilingual;
  headline: Bilingual;
  lead: Bilingual;
  accent: string;
  soft: string;
  previewLabel: Bilingual;
  features: readonly [Bilingual, Bilingual, Bilingual];
  wizardSteps: readonly [Bilingual, Bilingual, Bilingual, Bilingual];
};

const bi = (en: string, el: string): Bilingual => ({ en, el });
const feature = (en: string, el: string) => bi(en, el);

export const eventVerticals: readonly EventVertical[] = [
  { type: "engagement", symbol: "◇", accent: "#8f5f68", soft: "#f7e9eb", eyebrow: bi("Engagement & pre-wedding", "Αρραβώνας & προετοιμασία γάμου"), headline: bi("Begin the story before the wedding day.", "Η ιστορία ξεκινά πριν από την ημέρα του γάμου."), lead: bi("One private place for the proposal, pre-wedding photos, guests and every moment leading to the celebration.", "Ένας ιδιωτικός χώρος για την πρόταση, τις φωτογραφίες πριν από τον γάμο, τους καλεσμένους και κάθε στιγμή μέχρι τη γιορτή."), previewLabel: bi("A romantic timeline", "Μία ρομαντική διαδρομή"), features: [feature("Story & countdown", "Ιστορία & αντίστροφη μέτρηση"), feature("Pre-wedding gallery", "Συλλογή πριν από τον γάμο"), feature("Guest announcements", "Ενημερώσεις καλεσμένων")], wizardSteps: [bi("Your story", "Η ιστορία σας"), bi("Date & place", "Ημερομηνία & χώρος"), bi("Look & photos", "Εμφάνιση & φωτογραφίες"), bi("Guests & publish", "Καλεσμένοι & δημοσίευση")] },
  { type: "bachelor", symbol: "⚡", accent: "#f43f8f", soft: "#fff0f7", eyebrow: bi("Bachelor & bachelorette party", "Bachelor / Bachelorette πάρτι"), headline: bi("One last big night. Every moment in one place.", "Μία μεγάλη βραδιά. Όλες οι στιγμές σε ένα μέρος."), lead: bi("Plans, polls, secret updates, live uploads and the after-party album — without losing anything in the group chat.", "Πρόγραμμα, ψηφοφορίες, κρυφές ενημερώσεις, ζωντανά ανεβάσματα και το λεύκωμα μετά το πάρτι — χωρίς να χαθεί τίποτα στην ομαδική συνομιλία."), previewLabel: bi("The crew’s party hub", "Το κέντρο της παρέας"), features: [feature("Secret planning", "Κρυφή οργάνωση"), feature("Live photo drops", "Ζωντανό ανέβασμα φωτογραφιών"), feature("After-party album", "Λεύκωμα μετά το πάρτι")], wizardSteps: [bi("The crew", "Η παρέα"), bi("Plan the night", "Το πλάνο της βραδιάς"), bi("Mood & memories", "Ύφος & αναμνήσεις"), bi("Invite & go", "Πρόσκληση & φύγαμε")] },
  { type: "birthday", symbol: "✦", accent: "#7457a6", soft: "#eee9fa", eyebrow: bi("Birthday experience", "Η εμπειρία των γενεθλίων"), headline: bi("Turn one birthday into a shared story.", "Κάνε τα γενέθλια μία κοινή ιστορία."), lead: bi("Invitations, wishes, photos and live moments in one colorful page for every age.", "Προσκλητήριο, ευχές, φωτογραφίες και ζωντανές στιγμές σε μία πολύχρωμη σελίδα για κάθε ηλικία."), previewLabel: bi("The celebration hub", "Το κέντρο της γιορτής"), features: [feature("Invitation & countdown", "Πρόσκληση & αντίστροφη μέτρηση"), feature("Wish wall", "Τοίχος ευχών"), feature("Guest photo drops", "Φωτογραφίες καλεσμένων")], wizardSteps: [bi("Person & milestone", "Πρόσωπο & ηλικία"), bi("Party details", "Στοιχεία γιορτής"), bi("Theme & gallery", "Θέμα & συλλογή"), bi("Invite & launch", "Πρόσκληση & έναρξη")] },
  { type: "party", symbol: "✺", accent: "#c45173", soft: "#fde9f0", eyebrow: bi("Party & celebration", "Πάρτι & γιορτή"), headline: bi("Keep the energy alive before, during and after.", "Κράτησε την ενέργεια ζωντανή πριν, κατά τη διάρκεια και μετά."), lead: bi("A fast, social event page for invites, live uploads, music notes and the morning-after album.", "Μία ζωντανή σελίδα για προσκλήσεις, άμεσο ανέβασμα φωτογραφιών, μουσική και το λεύκωμα της επόμενης ημέρας."), previewLabel: bi("Live celebration feed", "Ζωντανή ροή της γιορτής"), features: [feature("Fast RSVP", "Γρήγορη επιβεβαίωση παρουσίας"), feature("Live photo wall", "Ζωντανός τοίχος φωτογραφιών"), feature("Aftermovie album", "Λεύκωμα μετά τη γιορτή")], wizardSteps: [bi("Party identity", "Ταυτότητα πάρτι"), bi("When & where", "Πότε & πού"), bi("Mood & media", "Ύφος & υλικό"), bi("Share", "Κοινοποίηση")] },
  { type: "baptism", symbol: "❈", accent: "#527f87", soft: "#e7f3f4", eyebrow: bi("Baptism & christening", "Βάπτιση"), headline: bi("A gentle digital keepsake for a meaningful day.", "Ένα τρυφερό ψηφιακό ενθύμιο για μία σημαντική ημέρα."), lead: bi("Share the invitation, ceremony details, family wishes and photographs in one protected place.", "Μοιράσου το προσκλητήριο, τα στοιχεία της τελετής, τις οικογενειακές ευχές και τις φωτογραφίες σε έναν προστατευμένο χώρο."), previewLabel: bi("A family keepsake", "Ένα οικογενειακό ενθύμιο"), features: [feature("Ceremony guide", "Οδηγός τελετής"), feature("Family guestbook", "Οικογενειακό ευχολόγιο"), feature("Private album", "Ιδιωτικό album")], wizardSteps: [bi("Child & family", "Παιδί & οικογένεια"), bi("Ceremony", "Τελετή"), bi("Keepsake style", "Ύφος ενθυμίου"), bi("Guests & privacy", "Καλεσμένοι & απόρρητο")] },
  { type: "baby", symbol: "◌", accent: "#b47771", soft: "#faece7", eyebrow: bi("Baby & family milestone", "Baby & οικογενειακό ορόσημο"), headline: bi("Collect the first chapter from everyone who cares.", "Συγκέντρωσε το πρώτο κεφάλαιο από όλους όσοι νοιάζονται."), lead: bi("Baby showers, first birthdays and family milestones with wishes, predictions and a private photo timeline.", "Baby shower, πρώτα γενέθλια και οικογενειακά ορόσημα με ευχές, προβλέψεις και ιδιωτικό φωτογραφικό timeline."), previewLabel: bi("The first chapter", "Το πρώτο κεφάλαιο"), features: [feature("Wish & prediction cards", "Ευχές & προβλέψεις"), feature("Family timeline", "Οικογενειακό timeline"), feature("Private sharing", "Ιδιωτική κοινοποίηση")], wizardSteps: [bi("Milestone", "Ορόσημο"), bi("Family details", "Οικογενειακά στοιχεία"), bi("Style & memories", "Ύφος & αναμνήσεις"), bi("Invite family", "Πρόσκληση οικογένειας")] },
  { type: "graduation", symbol: "△", accent: "#315f78", soft: "#e7f0f5", eyebrow: bi("Graduation & school", "Αποφοίτηση & σχολείο"), headline: bi("Celebrate the work, the people and what comes next.", "Γιόρτασε την προσπάθεια, τους ανθρώπους και όσα ακολουθούν."), lead: bi("A modern graduation page for ceremony information, class memories, messages and official photographs.", "Μία σύγχρονη σελίδα αποφοίτησης για πληροφορίες τελετής, αναμνήσεις τάξης, μηνύματα και επίσημες φωτογραφίες."), previewLabel: bi("The class story", "Η ιστορία της τάξης"), features: [feature("Ceremony details", "Στοιχεία τελετής"), feature("Class memory wall", "Τοίχος αναμνήσεων"), feature("Official album", "Επίσημο album")], wizardSteps: [bi("Graduate or class", "Απόφοιτος ή τάξη"), bi("Ceremony details", "Στοιχεία τελετής"), bi("School identity", "Ταυτότητα σχολείου"), bi("Class access", "Πρόσβαση τάξης")] },
  { type: "corporate", symbol: "▦", accent: "#275f57", soft: "#e4f0ed", eyebrow: bi("Corporate & business", "Εταιρικό & επαγγελματικό"), headline: bi("One branded hub for every attendee.", "Ένα branded hub για κάθε συμμετέχοντα."), lead: bi("Agenda, speakers, QR access, attendee uploads and post-event assets with clear team permissions.", "Agenda, ομιλητές, QR πρόσβαση, uploads συμμετεχόντων και υλικό μετά το event με σαφή δικαιώματα ομάδας."), previewLabel: bi("The attendee portal", "Το portal συμμετεχόντων"), features: [feature("Agenda & speakers", "Agenda & ομιλητές"), feature("Branded QR access", "Branded QR πρόσβαση"), feature("Team permissions", "Δικαιώματα ομάδας")], wizardSteps: [bi("Event objective", "Στόχος event"), bi("Agenda & venue", "Agenda & χώρος"), bi("Brand & speakers", "Brand & ομιλητές"), bi("Attendees & launch", "Συμμετέχοντες & έναρξη")] },
  { type: "trip", symbol: "⌁", accent: "#2d7481", soft: "#e2f2f4", eyebrow: bi("Trip & vacation", "Ταξίδι & διακοπές"), headline: bi("Everyone’s photos. One shared travel journal.", "Οι φωτογραφίες όλων. Ένα κοινό ταξιδιωτικό ημερολόγιο."), lead: bi("Build the itinerary, collect every perspective and keep a chronological album that survives the group chat.", "Οργάνωσε το πρόγραμμα, συγκέντρωσε κάθε οπτική και κράτησε ένα χρονολογικό album πέρα από το group chat."), previewLabel: bi("A shared travel journal", "Ένα κοινό travel journal"), features: [feature("Shared itinerary", "Κοινό πρόγραμμα"), feature("Location photo drops", "Φωτογραφίες ανά τοποθεσία"), feature("Chronological journal", "Χρονολογικό ημερολόγιο")], wizardSteps: [bi("Destination & group", "Προορισμός & παρέα"), bi("Dates & stops", "Ημερομηνίες & στάσεις"), bi("Journal style", "Ύφος ημερολογίου"), bi("Invite travelers", "Πρόσκληση ταξιδιωτών")] },
  { type: "reunion", symbol: "∞", accent: "#8a623e", soft: "#f4eadf", eyebrow: bi("Reunion & gathering", "Reunion & συνάντηση"), headline: bi("Bring the old stories and new moments together.", "Ένωσε τις παλιές ιστορίες με τις νέες στιγμές."), lead: bi("Reconnect a family, class or group with RSVP, then-and-now memories and one lasting shared archive.", "Επανένωσε οικογένεια, τάξη ή παρέα με RSVP, παλιές και νέες αναμνήσεις και ένα κοινό αρχείο."), previewLabel: bi("Then, now, together", "Τότε, τώρα, μαζί"), features: [feature("Who is coming", "Ποιοι θα έρθουν"), feature("Then & now gallery", "Gallery τότε & τώρα"), feature("Shared archive", "Κοινό αρχείο")], wizardSteps: [bi("The group", "Η ομάδα"), bi("Gathering details", "Στοιχεία συνάντησης"), bi("Archive & style", "Αρχείο & ύφος"), bi("Reconnect", "Επανασύνδεση")] },
  { type: "community", symbol: "◎", accent: "#a24a32", soft: "#f8e8e2", eyebrow: bi("Festival, concert & community", "Φεστιβάλ, συναυλία & κοινότητα"), headline: bi("Let the whole community contribute to the record.", "Άφησε όλη την κοινότητα να συνεισφέρει στην ιστορία."), lead: bi("A scalable event hub for schedules, stages, audience uploads, moderation and a curated official recap.", "Ένας ευέλικτος χώρος για πρόγραμμα, σκηνές, φωτογραφίες κοινού, έλεγχο περιεχομένου και επιλεγμένη επίσημη ανασκόπηση."), previewLabel: bi("The community live hub", "Το ζωντανό κέντρο της κοινότητας"), features: [feature("Schedule & stages", "Πρόγραμμα & σκηνές"), feature("Moderated uploads", "Ελεγχόμενα ανεβάσματα"), feature("Official recap", "Επίσημη ανασκόπηση")], wizardSteps: [bi("Event identity", "Ταυτότητα εκδήλωσης"), bi("Schedule & locations", "Πρόγραμμα & χώροι"), bi("Community branding", "Οπτική ταυτότητα κοινότητας"), bi("Access & moderation", "Πρόσβαση & έλεγχος περιεχομένου")] },
  { type: "memorial", symbol: "❧", accent: "#59685f", soft: "#edf0ed", eyebrow: bi("Memorial & celebration of life", "Μνημόσυνο & γιορτή ζωής"), headline: bi("Preserve a life through the stories people carry.", "Διατήρησε μία ζωή μέσα από τις ιστορίες των ανθρώπων."), lead: bi("A respectful private space for service information, photographs, memories and messages from family and friends.", "Ένας διακριτικός ιδιωτικός χώρος για πληροφορίες τελετής, φωτογραφίες, αναμνήσεις και μηνύματα οικογένειας και φίλων."), previewLabel: bi("A lasting remembrance", "Μία διαχρονική ανάμνηση"), features: [feature("Service information", "Πληροφορίες τελετής"), feature("Memory contributions", "Συνεισφορές αναμνήσεων"), feature("Family moderation", "Έγκριση οικογένειας")], wizardSteps: [bi("The person", "Το πρόσωπο"), bi("Service details", "Στοιχεία τελετής"), bi("Life & photographs", "Ζωή & φωτογραφίες"), bi("Family privacy", "Οικογενειακό απόρρητο")] },
  { type: "other", symbol: "✣", accent: "#556b63", soft: "#eaf0ed", eyebrow: bi("Custom event", "Event στα μέτρα σου"), headline: bi("Shape an event that does not fit a standard label.", "Δημιούργησε ένα event που δεν χωρά σε μία τυπική κατηγορία."), lead: bi("A flexible private page for any gathering, milestone or idea, with the structure you need and none you do not.", "Μία ευέλικτη ιδιωτική σελίδα για κάθε συνάντηση, ορόσημο ή ιδέα, μόνο με τη δομή που πραγματικά χρειάζεσαι."), previewLabel: bi("Your event, your structure", "Το event σου, με τη δική σου δομή"), features: [feature("Flexible event story", "Ευέλικτη ιστορία event"), feature("Custom schedule", "Προσαρμοσμένο πρόγραμμα"), feature("Private guest access", "Ιδιωτική πρόσβαση καλεσμένων")], wizardSteps: [bi("Event identity", "Ταυτότητα event"), bi("Dates & flow", "Ημερομηνίες & ροή"), bi("Style & story", "Ύφος & ιστορία"), bi("Guests & launch", "Καλεσμένοι & έναρξη")] },
] as const;

const translatedVerticalTexts: Partial<Record<Locale, Record<string, string>>> = {
  fr: {
    "Engagement & pre-wedding": "Fiançailles et avant-mariage",
    "Begin the story before the wedding day.": "Commencez l’histoire avant le jour du mariage.",
    "One private place for the proposal, pre-wedding photos, guests and every moment leading to the celebration.": "Un espace privé pour la demande, les photos d’avant-mariage, les invités et chaque moment jusqu’à la célébration.",
    "A romantic timeline": "Une chronologie romantique",
    "Story & countdown": "Histoire et compte à rebours",
    "Pre-wedding gallery": "Galerie d’avant-mariage",
    "Guest announcements": "Informations pour les invités",
    "Your story": "Votre histoire",
    "Date & place": "Date et lieu",
    "Look & photos": "Style et photos",
    "Guests & publish": "Invités et publication",
    "Bachelor & bachelorette party": "Enterrement de vie de célibataire",
    "One last big night. Every moment in one place.": "Une dernière grande soirée. Tous les moments au même endroit.",
    "Plans, polls, secret updates, live uploads and the after-party album — without losing anything in the group chat.": "Programme, sondages, informations secrètes, ajouts en direct et album d’après-soirée — sans rien perdre dans la discussion de groupe.",
    "The crew’s party hub": "Le quartier général de la soirée",
    "Secret planning": "Organisation secrète",
    "Live photo drops": "Photos ajoutées en direct",
    "After-party album": "Album d’après-soirée",
    "The crew": "La bande",
    "Plan the night": "Organiser la soirée",
    "Mood & memories": "Ambiance et souvenirs",
    "Invite & go": "Inviter et démarrer",
    "Birthday experience": "Expérience d’anniversaire",
    "Turn one birthday into a shared story.": "Transformez un anniversaire en une histoire partagée.",
    "Invitations, wishes, photos and live moments in one colorful page for every age.": "Invitations, vœux, photos et moments en direct sur une page colorée, pour tous les âges.",
    "The celebration hub": "Le centre de la fête",
    "Invitation & countdown": "Invitation et compte à rebours",
    "Wish wall": "Mur de vœux",
    "Guest photo drops": "Photos des invités",
    "Person & milestone": "Personne et âge célébré",
    "Party details": "Détails de la fête",
    "Theme & gallery": "Thème et galerie",
    "Invite & launch": "Inviter et lancer",
    "Party & celebration": "Fête et célébration",
    "Keep the energy alive before, during and after.": "Gardez l’énergie vivante avant, pendant et après.",
    "A fast, social event page for invites, live uploads, music notes and the morning-after album.": "Une page dynamique pour les invitations, les ajouts en direct, la musique et l’album du lendemain.",
    "Live celebration feed": "Fil de fête en direct",
    "Fast RSVP": "RSVP rapide",
    "Live photo wall": "Mur de photos en direct",
    "Aftermovie album": "Album d’après-fête",
    "Party identity": "Identité de la fête",
    "When & where": "Date et lieu",
    "Mood & media": "Ambiance et médias",
    "Share": "Partager",
    "Baptism & christening": "Baptême",
    "A gentle digital keepsake for a meaningful day.": "Un doux souvenir numérique pour une journée pleine de sens.",
    "Share the invitation, ceremony details, family wishes and photographs in one protected place.": "Partagez l’invitation, les détails de la cérémonie, les vœux de la famille et les photos dans un espace protégé.",
    "A family keepsake": "Un souvenir familial",
    "Ceremony guide": "Guide de la cérémonie",
    "Family guestbook": "Livre d’or familial",
    "Private album": "Album privé",
    "Child & family": "Enfant et famille",
    "Ceremony": "Cérémonie",
    "Keepsake style": "Style du souvenir",
    "Guests & privacy": "Invités et confidentialité",
    "Baby & family milestone": "Bébé et étape familiale",
    "Collect the first chapter from everyone who cares.": "Rassemblez le premier chapitre avec tous ceux qui comptent.",
    "Baby showers, first birthdays and family milestones with wishes, predictions and a private photo timeline.": "Baby showers, premiers anniversaires et étapes familiales avec vœux, prédictions et chronologie photo privée.",
    "The first chapter": "Le premier chapitre",
    "Wish & prediction cards": "Cartes de vœux et prédictions",
    "Family timeline": "Chronologie familiale",
    "Private sharing": "Partage privé",
    "Milestone": "Étape importante",
    "Family details": "Détails de la famille",
    "Style & memories": "Style et souvenirs",
    "Invite family": "Inviter la famille",
    "Graduation & school": "Diplôme et école",
    "Celebrate the work, the people and what comes next.": "Célébrez le travail accompli, les personnes présentes et la suite de l’aventure.",
    "A modern graduation page for ceremony information, class memories, messages and official photographs.": "Une page moderne pour les informations de cérémonie, les souvenirs de promotion, les messages et les photos officielles.",
    "The class story": "L’histoire de la promotion",
    "Ceremony details": "Détails de la cérémonie",
    "Class memory wall": "Mur de souvenirs de la promotion",
    "Official album": "Album officiel",
    "Graduate or class": "Diplômé ou promotion",
    "School identity": "Identité de l’établissement",
    "Class access": "Accès de la promotion",
    "Corporate & business": "Entreprise et professionnel",
    "One branded hub for every attendee.": "Un espace à votre image pour chaque participant.",
    "Agenda, speakers, QR access, attendee uploads and post-event assets with clear team permissions.": "Programme, intervenants, accès QR, ajouts des participants et contenus après l’événement avec des droits d’équipe clairs.",
    "The attendee portal": "Le portail des participants",
    "Agenda & speakers": "Programme et intervenants",
    "Branded QR access": "Accès QR personnalisé",
    "Team permissions": "Droits de l’équipe",
    "Event objective": "Objectif de l’événement",
    "Agenda & venue": "Programme et lieu",
    "Brand & speakers": "Marque et intervenants",
    "Attendees & launch": "Participants et lancement",
    "Reunion & gathering": "Retrouvailles et rassemblement",
    "Bring the old stories and new moments together.": "Réunissez les anciennes histoires et les nouveaux moments.",
    "Reconnect a family, class or group with RSVP, then-and-now memories and one lasting shared archive.": "Réunissez une famille, une promotion ou un groupe avec RSVP, souvenirs d’hier et d’aujourd’hui et une archive partagée durable.",
    "Then, now, together": "Hier, aujourd’hui, ensemble",
    "Who is coming": "Qui sera présent",
    "Then & now gallery": "Galerie d’hier et d’aujourd’hui",
    "Shared archive": "Archive partagée",
    "The group": "Le groupe",
    "Gathering details": "Détails des retrouvailles",
    "Archive & style": "Archive et style",
    "Reconnect": "Se retrouver",
    "Festival, concert & community": "Festival, concert et communauté",
    "Let the whole community contribute to the record.": "Permettez à toute la communauté de contribuer au souvenir collectif.",
    "A scalable event hub for schedules, stages, audience uploads, moderation and a curated official recap.": "Un espace évolutif pour les programmes, les scènes, les ajouts du public, la modération et un récapitulatif officiel sélectionné.",
    "The community live hub": "L’espace en direct de la communauté",
    "Schedule & stages": "Programme et scènes",
    "Moderated uploads": "Ajouts modérés",
    "Official recap": "Récapitulatif officiel",
    "Event identity": "Identité de l’événement",
    "Schedule & locations": "Programme et lieux",
    "Community branding": "Identité de la communauté",
    "Access & moderation": "Accès et modération",
    "Memorial & celebration of life": "Hommage et célébration de vie",
    "Preserve a life through the stories people carry.": "Préservez une vie à travers les histoires que chacun porte.",
    "A respectful private space for service information, photographs, memories and messages from family and friends.": "Un espace privé et respectueux pour les informations de cérémonie, les photos, les souvenirs et les messages des proches.",
    "A lasting remembrance": "Un souvenir durable",
    "Service information": "Informations sur la cérémonie",
    "Memory contributions": "Souvenirs partagés",
    "Family moderation": "Modération familiale",
    "The person": "La personne",
    "Service details": "Détails de la cérémonie",
    "Life & photographs": "Vie et photographies",
    "Family privacy": "Confidentialité familiale",
    "Custom event": "Événement personnalisé",
    "Shape an event that does not fit a standard label.": "Créez un événement qui ne correspond à aucune catégorie standard.",
    "A flexible private page for any gathering, milestone or idea, with the structure you need and none you do not.": "Une page privée et flexible pour toute rencontre, étape ou idée, avec uniquement la structure dont vous avez besoin.",
    "Your event, your structure": "Votre événement, votre structure",
    "Flexible event story": "Histoire d’événement flexible",
    "Custom schedule": "Programme personnalisé",
    "Private guest access": "Accès privé des invités",
    "Dates & flow": "Dates et déroulement",
    "Style & story": "Style et histoire",
    "Guests & launch": "Invités et lancement",
    "Trip & vacation": "Voyage et vacances",
    "Everyone’s photos. One shared travel journal.": "Les photos de tous. Un seul carnet de voyage partagé.",
    "Build the itinerary, collect every perspective and keep a chronological album that survives the group chat.": "Créez l’itinéraire, rassemblez tous les points de vue et conservez un album chronologique qui ne se perd pas dans la discussion de groupe.",
    "A shared travel journal": "Un carnet de voyage partagé",
    "Shared itinerary": "Itinéraire partagé",
    "Location photo drops": "Photos par destination",
    "Chronological journal": "Journal chronologique",
    "Destination & group": "Destination et groupe",
    "Dates & stops": "Dates et étapes",
    "Journal style": "Style du journal",
    "Invite travelers": "Inviter les voyageurs",
  },
  de: {
    "Engagement & pre-wedding": "Verlobung und Vorhochzeit",
    "Begin the story before the wedding day.": "Beginnt eure Geschichte schon vor dem Hochzeitstag.",
    "One private place for the proposal, pre-wedding photos, guests and every moment leading to the celebration.": "Ein privater Ort für den Antrag, Fotos vor der Hochzeit, Gäste und alle Momente bis zur Feier.",
    "A romantic timeline": "Eine romantische Zeitleiste",
    "Story & countdown": "Geschichte und Countdown",
    "Pre-wedding gallery": "Galerie vor der Hochzeit",
    "Guest announcements": "Informationen für Gäste",
    "Your story": "Eure Geschichte",
    "Date & place": "Datum und Ort",
    "Look & photos": "Stil und Fotos",
    "Guests & publish": "Gäste und Veröffentlichung",
    "Bachelor & bachelorette party": "Junggesellen- und Junggesellinnenabschied",
    "One last big night. Every moment in one place.": "Eine letzte große Nacht. Alle Momente an einem Ort.",
    "Plans, polls, secret updates, live uploads and the after-party album — without losing anything in the group chat.": "Planung, Abstimmungen, geheime Updates, Live-Uploads und das After-Party-Album — ohne dass etwas im Gruppenchat verloren geht.",
    "The crew’s party hub": "Die Party-Zentrale der Gruppe",
    "Secret planning": "Geheime Planung",
    "Live photo drops": "Live-Foto-Uploads",
    "After-party album": "After-Party-Album",
    "The crew": "Die Gruppe",
    "Plan the night": "Die Nacht planen",
    "Mood & memories": "Stimmung und Erinnerungen",
    "Invite & go": "Einladen und loslegen",
    "Birthday experience": "Geburtstagserlebnis",
    "Turn one birthday into a shared story.": "Macht aus einem Geburtstag eine gemeinsame Geschichte.",
    "Invitations, wishes, photos and live moments in one colorful page for every age.": "Einladungen, Wünsche, Fotos und Live-Momente auf einer farbenfrohen Seite für jedes Alter.",
    "The celebration hub": "Die Zentrale der Feier",
    "Invitation & countdown": "Einladung und Countdown",
    "Wish wall": "Wunschwand",
    "Guest photo drops": "Gästefotos",
    "Person & milestone": "Person und Meilenstein",
    "Party details": "Details der Feier",
    "Theme & gallery": "Thema und Galerie",
    "Invite & launch": "Einladen und starten",
    "Party & celebration": "Party und Feier",
    "Keep the energy alive before, during and after.": "Haltet die Energie davor, währenddessen und danach lebendig.",
    "A fast, social event page for invites, live uploads, music notes and the morning-after album.": "Eine lebendige Eventseite für Einladungen, Live-Uploads, Musikhinweise und das Album am nächsten Morgen.",
    "Live celebration feed": "Live-Feed der Feier",
    "Fast RSVP": "Schnelle Zusage",
    "Live photo wall": "Live-Fotowand",
    "Aftermovie album": "Aftermovie-Album",
    "Party identity": "Identität der Party",
    "When & where": "Wann und wo",
    "Mood & media": "Stimmung und Medien",
    "Share": "Teilen",
    "Baptism & christening": "Taufe",
    "A gentle digital keepsake for a meaningful day.": "Ein liebevolles digitales Andenken an einen besonderen Tag.",
    "Share the invitation, ceremony details, family wishes and photographs in one protected place.": "Teilt Einladung, Ablauf der Zeremonie, Wünsche der Familie und Fotos an einem geschützten Ort.",
    "A family keepsake": "Ein Familienandenken",
    "Ceremony guide": "Ablauf der Zeremonie",
    "Family guestbook": "Familien-Gästebuch",
    "Private album": "Privates Album",
    "Child & family": "Kind und Familie",
    "Ceremony": "Zeremonie",
    "Keepsake style": "Stil des Andenkens",
    "Guests & privacy": "Gäste und Privatsphäre",
    "Baby & family milestone": "Baby und Familienmeilenstein",
    "Collect the first chapter from everyone who cares.": "Sammelt das erste Kapitel mit allen, denen ihr am Herzen liegt.",
    "Baby showers, first birthdays and family milestones with wishes, predictions and a private photo timeline.": "Babypartys, erste Geburtstage und Familienmeilensteine mit Wünschen, Vorhersagen und einer privaten Fotochronik.",
    "The first chapter": "Das erste Kapitel",
    "Wish & prediction cards": "Wunsch- und Vorhersagekarten",
    "Family timeline": "Familienchronik",
    "Private sharing": "Privates Teilen",
    "Milestone": "Meilenstein",
    "Family details": "Familiendetails",
    "Style & memories": "Stil und Erinnerungen",
    "Invite family": "Familie einladen",
    "Graduation & school": "Abschluss und Schule",
    "Celebrate the work, the people and what comes next.": "Feiert die Leistung, die Menschen und alles, was als Nächstes kommt.",
    "A modern graduation page for ceremony information, class memories, messages and official photographs.": "Eine moderne Abschlussseite für Informationen zur Feier, Erinnerungen der Klasse, Nachrichten und offizielle Fotos.",
    "The class story": "Die Geschichte der Klasse",
    "Ceremony details": "Details der Abschlussfeier",
    "Class memory wall": "Erinnerungswand der Klasse",
    "Official album": "Offizielles Album",
    "Graduate or class": "Absolvent oder Klasse",
    "School identity": "Identität der Schule",
    "Class access": "Zugang der Klasse",
    "Corporate & business": "Unternehmen und Business",
    "One branded hub for every attendee.": "Eine gebrandete Zentrale für alle Teilnehmenden.",
    "Agenda, speakers, QR access, attendee uploads and post-event assets with clear team permissions.": "Agenda, Vortragende, QR-Zugang, Uploads der Teilnehmenden und Inhalte nach dem Event mit klaren Teamrechten.",
    "The attendee portal": "Das Portal für Teilnehmende",
    "Agenda & speakers": "Agenda und Vortragende",
    "Branded QR access": "Gebrandeter QR-Zugang",
    "Team permissions": "Teamrechte",
    "Event objective": "Ziel des Events",
    "Agenda & venue": "Agenda und Veranstaltungsort",
    "Brand & speakers": "Marke und Vortragende",
    "Attendees & launch": "Teilnehmende und Start",
    "Reunion & gathering": "Wiedersehen und Treffen",
    "Bring the old stories and new moments together.": "Bringt alte Geschichten und neue Momente zusammen.",
    "Reconnect a family, class or group with RSVP, then-and-now memories and one lasting shared archive.": "Verbindet Familie, Klasse oder Gruppe mit Zusagen, Erinnerungen von damals und heute und einem bleibenden gemeinsamen Archiv.",
    "Then, now, together": "Damals, heute, gemeinsam",
    "Who is coming": "Wer kommt",
    "Then & now gallery": "Galerie damals und heute",
    "Shared archive": "Gemeinsames Archiv",
    "The group": "Die Gruppe",
    "Gathering details": "Details des Treffens",
    "Archive & style": "Archiv und Stil",
    "Reconnect": "Wieder verbinden",
    "Festival, concert & community": "Festival, Konzert und Community",
    "Let the whole community contribute to the record.": "Lasst die ganze Community zur gemeinsamen Erinnerung beitragen.",
    "A scalable event hub for schedules, stages, audience uploads, moderation and a curated official recap.": "Eine skalierbare Eventzentrale für Zeitpläne, Bühnen, Publikums-Uploads, Moderation und einen kuratierten offiziellen Rückblick.",
    "The community live hub": "Die Live-Zentrale der Community",
    "Schedule & stages": "Zeitplan und Bühnen",
    "Moderated uploads": "Moderierte Uploads",
    "Official recap": "Offizieller Rückblick",
    "Event identity": "Identität des Events",
    "Schedule & locations": "Zeitplan und Orte",
    "Community branding": "Auftritt der Community",
    "Access & moderation": "Zugang und Moderation",
    "Memorial & celebration of life": "Gedenkfeier und Würdigung des Lebens",
    "Preserve a life through the stories people carry.": "Bewahrt ein Leben durch die Geschichten, die Menschen in sich tragen.",
    "A respectful private space for service information, photographs, memories and messages from family and friends.": "Ein respektvoller privater Ort für Informationen zur Gedenkfeier, Fotos, Erinnerungen und Nachrichten von Familie und Freunden.",
    "A lasting remembrance": "Eine bleibende Erinnerung",
    "Service information": "Informationen zur Gedenkfeier",
    "Memory contributions": "Geteilte Erinnerungen",
    "Family moderation": "Moderation durch die Familie",
    "The person": "Die Person",
    "Service details": "Details der Gedenkfeier",
    "Life & photographs": "Leben und Fotografien",
    "Family privacy": "Privatsphäre der Familie",
    "Custom event": "Individuelles Event",
    "Shape an event that does not fit a standard label.": "Gestaltet ein Event, das in keine vorgegebene Kategorie passt.",
    "A flexible private page for any gathering, milestone or idea, with the structure you need and none you do not.": "Eine flexible private Seite für jedes Treffen, jeden Meilenstein oder jede Idee – mit genau der Struktur, die ihr braucht.",
    "Your event, your structure": "Euer Event, eure Struktur",
    "Flexible event story": "Flexible Eventgeschichte",
    "Custom schedule": "Individueller Zeitplan",
    "Private guest access": "Privater Gästezugang",
    "Dates & flow": "Termine und Ablauf",
    "Style & story": "Stil und Geschichte",
    "Guests & launch": "Gäste und Start",
    "Trip & vacation": "Reise und Urlaub",
    "Everyone’s photos. One shared travel journal.": "Die Fotos von allen. Ein gemeinsames Reisetagebuch.",
    "Build the itinerary, collect every perspective and keep a chronological album that survives the group chat.": "Plant die Route, sammelt jede Perspektive und bewahrt ein chronologisches Album, das nicht im Gruppenchat verschwindet.",
    "A shared travel journal": "Ein gemeinsames Reisetagebuch",
    "Shared itinerary": "Gemeinsamer Reiseplan",
    "Location photo drops": "Fotos nach Reiseziel",
    "Chronological journal": "Chronologisches Tagebuch",
    "Destination & group": "Reiseziel und Gruppe",
    "Dates & stops": "Termine und Stationen",
    "Journal style": "Stil des Tagebuchs",
    "Invite travelers": "Mitreisende einladen",
  },
  es: {
    "Engagement & pre-wedding": "Compromiso y preboda",
    "Begin the story before the wedding day.": "Empieza la historia antes del día de la boda.",
    "One private place for the proposal, pre-wedding photos, guests and every moment leading to the celebration.": "Un espacio privado para la propuesta, las fotos de preboda, los invitados y cada momento previo a la celebración.",
    "A romantic timeline": "Una cronología romántica",
    "Story & countdown": "Historia y cuenta atrás",
    "Pre-wedding gallery": "Galería de preboda",
    "Guest announcements": "Avisos para los invitados",
    "Your story": "Vuestra historia",
    "Date & place": "Fecha y lugar",
    "Look & photos": "Estilo y fotos",
    "Guests & publish": "Invitados y publicación",
    "Bachelor & bachelorette party": "Despedida de soltero o soltera",
    "One last big night. Every moment in one place.": "Una última gran noche. Todos los momentos en un solo lugar.",
    "Plans, polls, secret updates, live uploads and the after-party album — without losing anything in the group chat.": "Planes, encuestas, avisos secretos, subidas en directo y el álbum posterior — sin perder nada en el chat del grupo.",
    "The crew’s party hub": "El centro de la fiesta del grupo",
    "Secret planning": "Planificación secreta",
    "Live photo drops": "Fotos en directo",
    "After-party album": "Álbum de después de la fiesta",
    "The crew": "El grupo",
    "Plan the night": "Planificar la noche",
    "Mood & memories": "Ambiente y recuerdos",
    "Invite & go": "Invitar y empezar",
    "Birthday experience": "Experiencia de cumpleaños",
    "Turn one birthday into a shared story.": "Convierte un cumpleaños en una historia compartida.",
    "Invitations, wishes, photos and live moments in one colorful page for every age.": "Invitaciones, deseos, fotos y momentos en directo en una página llena de color para cualquier edad.",
    "The celebration hub": "El centro de la celebración",
    "Invitation & countdown": "Invitación y cuenta atrás",
    "Wish wall": "Muro de deseos",
    "Guest photo drops": "Fotos de los invitados",
    "Person & milestone": "Persona y momento especial",
    "Party details": "Detalles de la fiesta",
    "Theme & gallery": "Tema y galería",
    "Invite & launch": "Invitar y lanzar",
    "Party & celebration": "Fiesta y celebración",
    "Keep the energy alive before, during and after.": "Mantén viva la energía antes, durante y después.",
    "A fast, social event page for invites, live uploads, music notes and the morning-after album.": "Una página dinámica para invitaciones, subidas en directo, música y el álbum del día siguiente.",
    "Live celebration feed": "Feed de la celebración en directo",
    "Fast RSVP": "Confirmación rápida",
    "Live photo wall": "Muro de fotos en directo",
    "Aftermovie album": "Álbum posterior a la fiesta",
    "Party identity": "Identidad de la fiesta",
    "When & where": "Cuándo y dónde",
    "Mood & media": "Ambiente y contenido",
    "Share": "Compartir",
    "Baptism & christening": "Bautizo",
    "A gentle digital keepsake for a meaningful day.": "Un delicado recuerdo digital para un día lleno de significado.",
    "Share the invitation, ceremony details, family wishes and photographs in one protected place.": "Comparte la invitación, los detalles de la ceremonia, los deseos de la familia y las fotos en un espacio protegido.",
    "A family keepsake": "Un recuerdo familiar",
    "Ceremony guide": "Guía de la ceremonia",
    "Family guestbook": "Libro de firmas familiar",
    "Private album": "Álbum privado",
    "Child & family": "Niño y familia",
    "Ceremony": "Ceremonia",
    "Keepsake style": "Estilo del recuerdo",
    "Guests & privacy": "Invitados y privacidad",
    "Baby & family milestone": "Bebé y momento familiar",
    "Collect the first chapter from everyone who cares.": "Reúne el primer capítulo con todos los que os quieren.",
    "Baby showers, first birthdays and family milestones with wishes, predictions and a private photo timeline.": "Baby showers, primeros cumpleaños y momentos familiares con deseos, predicciones y una cronología fotográfica privada.",
    "The first chapter": "El primer capítulo",
    "Wish & prediction cards": "Tarjetas de deseos y predicciones",
    "Family timeline": "Cronología familiar",
    "Private sharing": "Compartir en privado",
    "Milestone": "Momento especial",
    "Family details": "Detalles de la familia",
    "Style & memories": "Estilo y recuerdos",
    "Invite family": "Invitar a la familia",
    "Graduation & school": "Graduación y escuela",
    "Celebrate the work, the people and what comes next.": "Celebra el esfuerzo, a las personas y todo lo que viene después.",
    "A modern graduation page for ceremony information, class memories, messages and official photographs.": "Una página moderna para la información de la ceremonia, recuerdos de la promoción, mensajes y fotografías oficiales.",
    "The class story": "La historia de la promoción",
    "Ceremony details": "Detalles de la ceremonia",
    "Class memory wall": "Muro de recuerdos de la promoción",
    "Official album": "Álbum oficial",
    "Graduate or class": "Graduado o promoción",
    "School identity": "Identidad del centro",
    "Class access": "Acceso de la promoción",
    "Corporate & business": "Corporativo y empresarial",
    "One branded hub for every attendee.": "Un espacio de marca para cada asistente.",
    "Agenda, speakers, QR access, attendee uploads and post-event assets with clear team permissions.": "Agenda, ponentes, acceso QR, subidas de asistentes y materiales posteriores con permisos de equipo claros.",
    "The attendee portal": "El portal de los asistentes",
    "Agenda & speakers": "Agenda y ponentes",
    "Branded QR access": "Acceso QR de marca",
    "Team permissions": "Permisos del equipo",
    "Event objective": "Objetivo del evento",
    "Agenda & venue": "Agenda y lugar",
    "Brand & speakers": "Marca y ponentes",
    "Attendees & launch": "Asistentes y lanzamiento",
    "Reunion & gathering": "Reencuentro y reunión",
    "Bring the old stories and new moments together.": "Reúne las historias de antes con los nuevos momentos.",
    "Reconnect a family, class or group with RSVP, then-and-now memories and one lasting shared archive.": "Vuelve a reunir a una familia, promoción o grupo con confirmaciones, recuerdos de antes y ahora y un archivo compartido duradero.",
    "Then, now, together": "Antes, ahora, juntos",
    "Who is coming": "Quién viene",
    "Then & now gallery": "Galería de antes y ahora",
    "Shared archive": "Archivo compartido",
    "The group": "El grupo",
    "Gathering details": "Detalles del encuentro",
    "Archive & style": "Archivo y estilo",
    "Reconnect": "Volver a conectar",
    "Festival, concert & community": "Festival, concierto y comunidad",
    "Let the whole community contribute to the record.": "Haz que toda la comunidad contribuya al recuerdo colectivo.",
    "A scalable event hub for schedules, stages, audience uploads, moderation and a curated official recap.": "Un espacio escalable para horarios, escenarios, subidas del público, moderación y un resumen oficial seleccionado.",
    "The community live hub": "El centro en directo de la comunidad",
    "Schedule & stages": "Programa y escenarios",
    "Moderated uploads": "Subidas moderadas",
    "Official recap": "Resumen oficial",
    "Event identity": "Identidad del evento",
    "Schedule & locations": "Programa y ubicaciones",
    "Community branding": "Identidad de la comunidad",
    "Access & moderation": "Acceso y moderación",
    "Memorial & celebration of life": "Homenaje y celebración de la vida",
    "Preserve a life through the stories people carry.": "Conserva una vida a través de las historias que guardan las personas.",
    "A respectful private space for service information, photographs, memories and messages from family and friends.": "Un espacio privado y respetuoso para información de la ceremonia, fotografías, recuerdos y mensajes de familiares y amigos.",
    "A lasting remembrance": "Un recuerdo duradero",
    "Service information": "Información de la ceremonia",
    "Memory contributions": "Recuerdos compartidos",
    "Family moderation": "Moderación familiar",
    "The person": "La persona",
    "Service details": "Detalles de la ceremonia",
    "Life & photographs": "Vida y fotografías",
    "Family privacy": "Privacidad familiar",
    "Custom event": "Evento personalizado",
    "Shape an event that does not fit a standard label.": "Da forma a un evento que no encaja en una categoría estándar.",
    "A flexible private page for any gathering, milestone or idea, with the structure you need and none you do not.": "Una página privada y flexible para cualquier encuentro, momento especial o idea, con solo la estructura que necesitas.",
    "Your event, your structure": "Tu evento, tu estructura",
    "Flexible event story": "Historia de evento flexible",
    "Custom schedule": "Programa personalizado",
    "Private guest access": "Acceso privado para invitados",
    "Dates & flow": "Fechas y desarrollo",
    "Style & story": "Estilo e historia",
    "Guests & launch": "Invitados y lanzamiento",
    "Trip & vacation": "Viaje y vacaciones",
    "Everyone’s photos. One shared travel journal.": "Las fotos de todos. Un diario de viaje compartido.",
    "Build the itinerary, collect every perspective and keep a chronological album that survives the group chat.": "Crea el itinerario, reúne cada punto de vista y conserva un álbum cronológico que no se pierda en el chat del grupo.",
    "A shared travel journal": "Un diario de viaje compartido",
    "Shared itinerary": "Itinerario compartido",
    "Location photo drops": "Fotos por destino",
    "Chronological journal": "Diario cronológico",
    "Destination & group": "Destino y grupo",
    "Dates & stops": "Fechas y paradas",
    "Journal style": "Estilo del diario",
    "Invite travelers": "Invitar a los viajeros",
  },
  it: {
    "Engagement & pre-wedding": "Fidanzamento e pre-matrimonio",
    "Begin the story before the wedding day.": "Inizia la storia prima del giorno del matrimonio.",
    "One private place for the proposal, pre-wedding photos, guests and every moment leading to the celebration.": "Uno spazio privato per la proposta, le foto prematrimoniali, gli invitati e ogni momento che precede la festa.",
    "A romantic timeline": "Una timeline romantica",
    "Story & countdown": "Storia e conto alla rovescia",
    "Pre-wedding gallery": "Galleria prematrimoniale",
    "Guest announcements": "Informazioni per gli invitati",
    "Your story": "La vostra storia",
    "Date & place": "Data e luogo",
    "Look & photos": "Stile e foto",
    "Guests & publish": "Invitati e pubblicazione",
    "Bachelor & bachelorette party": "Addio al celibato o al nubilato",
    "One last big night. Every moment in one place.": "Un’ultima grande serata. Ogni momento in un solo posto.",
    "Plans, polls, secret updates, live uploads and the after-party album — without losing anything in the group chat.": "Programma, sondaggi, aggiornamenti segreti, caricamenti live e album del dopo festa — senza perdere nulla nella chat di gruppo.",
    "The crew’s party hub": "Il centro della festa del gruppo",
    "Secret planning": "Organizzazione segreta",
    "Live photo drops": "Foto caricate in diretta",
    "After-party album": "Album del dopo festa",
    "The crew": "Il gruppo",
    "Plan the night": "Organizzare la serata",
    "Mood & memories": "Atmosfera e ricordi",
    "Invite & go": "Invita e inizia",
    "Birthday experience": "Esperienza di compleanno",
    "Turn one birthday into a shared story.": "Trasforma un compleanno in una storia condivisa.",
    "Invitations, wishes, photos and live moments in one colorful page for every age.": "Inviti, auguri, foto e momenti live in una pagina colorata per ogni età.",
    "The celebration hub": "Il centro della festa",
    "Invitation & countdown": "Invito e conto alla rovescia",
    "Wish wall": "Bacheca degli auguri",
    "Guest photo drops": "Foto degli invitati",
    "Person & milestone": "Persona e traguardo",
    "Party details": "Dettagli della festa",
    "Theme & gallery": "Tema e galleria",
    "Invite & launch": "Invita e pubblica",
    "Party & celebration": "Festa e celebrazione",
    "Keep the energy alive before, during and after.": "Mantieni viva l’energia prima, durante e dopo.",
    "A fast, social event page for invites, live uploads, music notes and the morning-after album.": "Una pagina dinamica per inviti, caricamenti live, musica e l’album del giorno dopo.",
    "Live celebration feed": "Feed live della festa",
    "Fast RSVP": "RSVP rapido",
    "Live photo wall": "Bacheca fotografica live",
    "Aftermovie album": "Album del dopo festa",
    "Party identity": "Identità della festa",
    "When & where": "Quando e dove",
    "Mood & media": "Atmosfera e contenuti",
    "Share": "Condividi",
    "Baptism & christening": "Battesimo",
    "A gentle digital keepsake for a meaningful day.": "Un delicato ricordo digitale per una giornata importante.",
    "Share the invitation, ceremony details, family wishes and photographs in one protected place.": "Condividi l’invito, i dettagli della cerimonia, gli auguri della famiglia e le fotografie in uno spazio protetto.",
    "A family keepsake": "Un ricordo di famiglia",
    "Ceremony guide": "Guida alla cerimonia",
    "Family guestbook": "Guestbook di famiglia",
    "Private album": "Album privato",
    "Child & family": "Bambino e famiglia",
    "Ceremony": "Cerimonia",
    "Keepsake style": "Stile del ricordo",
    "Guests & privacy": "Invitati e privacy",
    "Baby & family milestone": "Bebè e traguardo di famiglia",
    "Collect the first chapter from everyone who cares.": "Raccogli il primo capitolo con tutte le persone che vi vogliono bene.",
    "Baby showers, first birthdays and family milestones with wishes, predictions and a private photo timeline.": "Baby shower, primi compleanni e traguardi familiari con auguri, pronostici e una timeline fotografica privata.",
    "The first chapter": "Il primo capitolo",
    "Wish & prediction cards": "Biglietti di auguri e pronostici",
    "Family timeline": "Timeline di famiglia",
    "Private sharing": "Condivisione privata",
    "Milestone": "Traguardo",
    "Family details": "Dettagli della famiglia",
    "Style & memories": "Stile e ricordi",
    "Invite family": "Invita la famiglia",
    "Graduation & school": "Diploma, laurea e scuola",
    "Celebrate the work, the people and what comes next.": "Celebra il percorso, le persone e ciò che verrà.",
    "A modern graduation page for ceremony information, class memories, messages and official photographs.": "Una pagina moderna per informazioni sulla cerimonia, ricordi della classe, messaggi e fotografie ufficiali.",
    "The class story": "La storia della classe",
    "Ceremony details": "Dettagli della cerimonia",
    "Class memory wall": "Bacheca dei ricordi della classe",
    "Official album": "Album ufficiale",
    "Graduate or class": "Diplomato, laureato o classe",
    "School identity": "Identità della scuola",
    "Class access": "Accesso della classe",
    "Corporate & business": "Aziendale e professionale",
    "One branded hub for every attendee.": "Un hub coordinato al brand per ogni partecipante.",
    "Agenda, speakers, QR access, attendee uploads and post-event assets with clear team permissions.": "Agenda, relatori, accesso QR, caricamenti dei partecipanti e materiali post-evento con permessi chiari per il team.",
    "The attendee portal": "Il portale dei partecipanti",
    "Agenda & speakers": "Agenda e relatori",
    "Branded QR access": "Accesso QR personalizzato",
    "Team permissions": "Permessi del team",
    "Event objective": "Obiettivo dell’evento",
    "Agenda & venue": "Agenda e sede",
    "Brand & speakers": "Brand e relatori",
    "Attendees & launch": "Partecipanti e lancio",
    "Reunion & gathering": "Riunione e ritrovo",
    "Bring the old stories and new moments together.": "Unisci le vecchie storie ai nuovi momenti.",
    "Reconnect a family, class or group with RSVP, then-and-now memories and one lasting shared archive.": "Riunisci famiglia, classe o gruppo con RSVP, ricordi di ieri e di oggi e un archivio condiviso che rimane.",
    "Then, now, together": "Ieri, oggi, insieme",
    "Who is coming": "Chi partecipa",
    "Then & now gallery": "Galleria ieri e oggi",
    "Shared archive": "Archivio condiviso",
    "The group": "Il gruppo",
    "Gathering details": "Dettagli del ritrovo",
    "Archive & style": "Archivio e stile",
    "Reconnect": "Ritrovarsi",
    "Festival, concert & community": "Festival, concerto e comunità",
    "Let the whole community contribute to the record.": "Permetti a tutta la comunità di contribuire al ricordo collettivo.",
    "A scalable event hub for schedules, stages, audience uploads, moderation and a curated official recap.": "Un hub scalabile per programmi, palchi, caricamenti del pubblico, moderazione e un riepilogo ufficiale curato.",
    "The community live hub": "L’hub live della comunità",
    "Schedule & stages": "Programma e palchi",
    "Moderated uploads": "Caricamenti moderati",
    "Official recap": "Riepilogo ufficiale",
    "Event identity": "Identità dell’evento",
    "Schedule & locations": "Programma e luoghi",
    "Community branding": "Identità della comunità",
    "Access & moderation": "Accesso e moderazione",
    "Memorial & celebration of life": "Commemorazione e celebrazione della vita",
    "Preserve a life through the stories people carry.": "Custodisci una vita attraverso le storie che le persone portano con sé.",
    "A respectful private space for service information, photographs, memories and messages from family and friends.": "Uno spazio privato e rispettoso per informazioni sulla cerimonia, fotografie, ricordi e messaggi di familiari e amici.",
    "A lasting remembrance": "Un ricordo che rimane",
    "Service information": "Informazioni sulla cerimonia",
    "Memory contributions": "Ricordi condivisi",
    "Family moderation": "Moderazione della famiglia",
    "The person": "La persona",
    "Service details": "Dettagli della cerimonia",
    "Life & photographs": "Vita e fotografie",
    "Family privacy": "Privacy della famiglia",
    "Custom event": "Evento personalizzato",
    "Shape an event that does not fit a standard label.": "Crea un evento che non rientra in una categoria standard.",
    "A flexible private page for any gathering, milestone or idea, with the structure you need and none you do not.": "Una pagina privata e flessibile per qualsiasi incontro, traguardo o idea, con solo la struttura di cui hai bisogno.",
    "Your event, your structure": "Il tuo evento, la tua struttura",
    "Flexible event story": "Storia dell’evento flessibile",
    "Custom schedule": "Programma personalizzato",
    "Private guest access": "Accesso privato per gli invitati",
    "Dates & flow": "Date e svolgimento",
    "Style & story": "Stile e storia",
    "Guests & launch": "Invitati e lancio",
    "Trip & vacation": "Viaggio e vacanza",
    "Everyone’s photos. One shared travel journal.": "Le foto di tutti. Un unico diario di viaggio condiviso.",
    "Build the itinerary, collect every perspective and keep a chronological album that survives the group chat.": "Crea l’itinerario, raccogli ogni punto di vista e conserva un album cronologico che non si perda nella chat di gruppo.",
    "A shared travel journal": "Un diario di viaggio condiviso",
    "Shared itinerary": "Itinerario condiviso",
    "Location photo drops": "Foto per destinazione",
    "Chronological journal": "Diario cronologico",
    "Destination & group": "Destinazione e gruppo",
    "Dates & stops": "Date e tappe",
    "Journal style": "Stile del diario",
    "Invite travelers": "Invita i viaggiatori",
  },
};

export function eventVerticalFor(value: unknown) {
  return eventVerticals.find((vertical) => vertical.type === value) ?? null;
}

export function verticalText(value: Bilingual, locale: Locale) {
  if (locale === "el") return value.el;
  return translatedVerticalTexts[locale]?.[value.en] ?? value.en;
}
